import { test, expect } from '@playwright/test'

test('logo, signup, user ID login, owner activation and student portal work', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1024 })
  await page.goto('/')
  const logo = page.getByRole('img', { name: 'MS Digital Library logo' })
  await expect(logo).toBeVisible()
  await expect(logo).toHaveJSProperty('naturalWidth', 2000)
  await page.screenshot({ path: 'artifacts/login-logo-desktop.png', fullPage: true })
  await page.getByRole('button', { name: 'New user? Create an account' }).click()
  await page.getByLabel('Full name', { exact: true }).fill('Student Account Test')
  await page.getByLabel('User ID', { exact: true }).fill('browserstudent')
  await page.getByLabel('Password', { exact: true }).fill('browser-student-password')
  await page.getByLabel('Confirm password').fill('does-not-match-yet')
  await page.getByRole('button', { name: 'Create account', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Passwords do not match')
  await page.getByLabel('Confirm password').fill('browser-student-password')
  await page.screenshot({ path: 'artifacts/signup-logo-desktop.png', fullPage: true })
  await page.getByRole('button', { name: 'Create account', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('Account created')
  await expect(page.getByLabel('User ID or email')).toHaveValue('browserstudent')
  await page.getByLabel('Password', { exact: true }).fill('browser-student-password')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Your account is ready' })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Students', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Sign out', exact: true }).click()
  await page.getByRole('button', { name: 'Open demo workspace' }).click()
  await page.getByRole('link', { name: 'Settings', exact: true }).click()
  const account = page.getByRole('form', { name: 'Access for browserstudent' })
  await account.getByLabel('Access level').selectOption('student')
  await account.getByLabel('Student membership').selectOption('MSL-0084')
  await account.getByRole('button', { name: 'Save access' }).click()
  await expect(
    page.getByText('Access saved for browserstudent. They can sign in again.'),
  ).toBeVisible()
  await page.getByRole('button', { name: 'Sign out', exact: true }).click()
  await page.getByLabel('User ID or email').fill('browserstudent')
  await page.getByLabel('Password', { exact: true }).fill('browser-student-password')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'My Library Membership' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Priya Sharma', exact: true })).toBeVisible()
  await expect(page.getByText('Rahul Verma', { exact: true })).toHaveCount(0)
  await page.reload()
  await expect(page.getByRole('heading', { name: 'My Library Membership' })).toBeVisible()
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.locator('body')).toHaveJSProperty('scrollWidth', 390)
  await page.getByRole('button', { name: 'Sign out', exact: true }).click()
  await page.getByRole('button', { name: 'New user? Create an account' }).click()
  await expect(page.locator('body')).toHaveJSProperty('scrollWidth', 390)
  await page.screenshot({ path: 'artifacts/signup-logo-mobile.png', fullPage: true })
})
