import { test, expect } from '@playwright/test'

test('owner configures seats and reminders, corrects fees, and edits attendance', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1024 })
  await page.goto('/')
  await page.getByRole('button', { name: 'Open demo workspace' }).click()
  const go = (name: string) => page.getByRole('link', { name, exact: true }).click()
  await go('Seats & Attendance')
  await expect(page.locator('button.seat')).toHaveCount(54)
  await expect(page.locator('.seat-row')).toHaveCount(6)
  await expect(page.locator('.seat-row').first().locator('button')).toHaveCount(9)
  await go('Settings')
  await page.getByLabel('Seats per row').fill('10')
  await page.getByLabel('Floor / room name').fill('Study Hall')
  await page.getByLabel('Reminder message template').fill('Hello {name}, please pay {amount} to {library}. Your seat is {seat}.')
  await page.getByRole('button', { name: 'Save settings', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('Configuration saved')
  await go('Seats & Attendance')
  await expect(page.locator('button.seat')).toHaveCount(60)
  await page.reload()
  await expect(page.locator('button.seat')).toHaveCount(60)
  await go('Settings')
  await page.getByLabel('Seats per row').fill('9')
  await page.getByRole('button', { name: 'Save settings', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('Configuration saved')
  await go('Notifications')
  await expect(page.locator('.message-preview')).toContainText('please pay')
  await go('Students')
  await page.getByRole('textbox', { name: 'Search students' }).fill('Priya Sharma')
  await page.getByRole('button', { name: 'Edit', exact: true }).click()
  await page.getByLabel('Agreed monthly fee (₹)').fill('350')
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(page.locator('.student-profile')).toContainText('₹350/month')
  await go('Fees & Payments')
  const receiptButton = page.getByRole('button', { name: /^MSL-R/ }).first()
  const receipt = await receiptButton.innerText()
  await receiptButton.click()
  await page.getByRole('button', { name: 'Edit payment', exact: true }).click()
  await page.getByLabel('Amount received (₹)').fill('450')
  await page.getByLabel('Reason for correction').fill('Corrected amount in register')
  await page.getByRole('button', { name: 'Save correction', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByRole('button', { name: receipt, exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('₹450')
  await page.getByRole('button', { name: 'Void receipt', exact: true }).click()
  await page.getByLabel('Reason for correction').fill('Receipt needs review')
  await page.getByRole('button', { name: 'Save correction', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByLabel('Receipt status').selectOption('voided')
  await page.getByRole('button', { name: `${receipt} (voided)`, exact: true }).click()
  await page.getByRole('button', { name: 'Restore receipt', exact: true }).click()
  await page.getByLabel('Reason for correction').fill('Verified payment received')
  await page.getByRole('button', { name: 'Save correction', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await go('Seats & Attendance')
  await page.getByRole('button', { name: 'All dates', exact: true }).click()
  await page.getByLabel('Search attendance').fill('Priya Sharma')
  await page.getByRole('button', { name: 'Edit attendance for Priya Sharma', exact: true }).click()
  await page.getByLabel('Attendance note').fill('Attendance verified by owner')
  await page.getByLabel('Reason for correction').fill('Added verification note')
  await page.getByRole('button', { name: 'Save correction', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByText('Attendance verified by owner', { exact: true })).toBeVisible()
  await go('Settings')
  await expect(page.locator('.audit-list')).toContainText('payment.save')
  await expect(page.locator('.audit-list')).toContainText('attendance.save')
})
