import { test, expect } from '@playwright/test'
import { mkdirSync } from 'node:fs'

test('owner can navigate, manage a membership, collect fees, and check attendance', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', e => errors.push(e.message))
  await page.goto('/')
  await page.getByRole('button', { name: 'Open demo workspace' }).click()
  await expect(page.getByRole('heading', { name: 'Library Overview' })).toBeVisible()
  mkdirSync('artifacts', { recursive: true })
  await page.setViewportSize({ width: 1440, height: 1024 })
  await page.screenshot({ path: 'artifacts/dashboard-desktop.png', fullPage: true })
  await page.getByRole('link', { name: 'Students', exact: true }).click()
  await page.getByRole('button', { name: 'Add New Student' }).click()
  const name = `Browser Student ${Date.now()}`
  await page.getByLabel('Full name').fill(name)
  await page.getByLabel('Mobile number').fill(`9${String(Date.now()).slice(-9)}`)
  await page.getByLabel('Membership plan').selectOption('8h')
  await page.getByLabel('Assigned seat').selectOption('F-09')
  await page.getByRole('button', { name: 'Add student', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByRole('textbox', { name: 'Search students' }).fill(name)
  await expect(page.getByRole('heading', { name, exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Check-in', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Check-out', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Collect Fee', exact: true }).click()
  await page.getByRole('button', { name: 'Record payment' }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.locator('tbody').getByText('Paid', { exact: true })).toBeVisible()
  await page.reload()
  await page.getByRole('textbox', { name: 'Search students' }).fill(name)
  await expect(page.getByRole('heading', { name, exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Collect Fee', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Record payment' })).toBeDisabled()
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  await page.getByRole('button', { name: 'Check-out', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Check-in', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Archive membership' }).click()
  await page.getByRole('button', { name: 'Archive student', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByRole('button', { name: 'Dismiss notification' }).click()
  for (const [link, heading] of [['Seats & Attendance', 'Seats & Attendance'], ['Fees & Payments', 'Fees & Payments'], ['Timings & Plans', 'Timing & Membership Plans'], ['Reports', 'Reports & Analytics'], ['Notifications', 'Fee Reminder Notifications'], ['Settings', 'Library Settings']]) {
    await page.getByRole('link', { name: link, exact: true }).click()
    await expect(page.getByRole('heading', { name: heading, exact: true })).toBeVisible()
    await page.screenshot({ path: `artifacts/${link.split(' ')[0].toLowerCase()}-desktop.png`, fullPage: true })
  }
  await page.getByRole('link', { name: 'Reports', exact: true }).click()
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: /Student Master Database/ }).click()
  expect((await download).suggestedFilename()).toBe('student-database.csv')
  await page.getByRole('button', { name: 'Dismiss notification' }).click()
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('button', { name: 'Open navigation' }).click()
  await page.getByRole('link', { name: 'Dashboard', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Library Overview' })).toBeVisible()
  await expect(page.locator('body')).toHaveJSProperty('scrollWidth', 390)
  await page.screenshot({ path: 'artifacts/dashboard-mobile.png', fullPage: true })
  expect(errors).toEqual([])
})

test('every screen fits a mobile viewport and the dialog supports keyboard dismissal', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await page.getByRole('button', { name: 'Open demo workspace' }).click()
  for (const link of ['Dashboard', 'Students', 'Seats & Attendance', 'Fees & Payments', 'Timings & Plans', 'Reports', 'Notifications', 'Settings']) {
    await page.getByRole('button', { name: 'Open navigation' }).click()
    await page.getByRole('link', { name: link, exact: true }).click()
    await expect(page.locator('body')).toHaveJSProperty('scrollWidth', 390)
  }
  await page.getByRole('button', { name: 'Open navigation' }).click()
  await page.getByRole('link', { name: 'Students', exact: true }).click()
  await page.getByRole('button', { name: 'Add New Student' }).click()
  await expect(page.getByLabel('Full name')).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Add New Student' })).toBeFocused()
  await page.getByRole('button', { name: 'Open navigation' }).click()
  await page.getByRole('link', { name: 'Fees & Payments', exact: true }).click()
  await page.getByLabel('Report month').fill('2027-01')
  await page.getByRole('button', { name: 'Collect Fee', exact: true }).click()
  await expect(page.getByLabel('Billing month')).toHaveValue('2027-01')
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  await page.getByRole('button', { name: 'Open navigation' }).click()
  await page.getByRole('link', { name: 'Seats & Attendance', exact: true }).click()
  await page.getByRole('button', { name: 'Seat F-09, available', exact: true }).click()
  await page.getByRole('button', { name: 'Add student', exact: true }).click()
  await expect(page.getByLabel('Assigned seat')).toHaveValue('F-09')
})
