import { test, expect } from '@playwright/test'

test('owner sends demo notifications, retains drafts, and edits opening and study hours', async ({
  page,
}) => {
  await page.setViewportSize({ width: 1440, height: 1024 })
  await page.goto('/')
  await page.getByRole('button', { name: 'Open demo workspace' }).click()
  const go = (name: string) => page.getByRole('link', { name, exact: true }).click()
  await go('Notifications')
  await page.getByRole('button', { name: /^Simulate fee reminders/ }).click()
  await expect(page.getByRole('status')).toContainText('simulated')
  await expect(page.locator('.notification-history')).toContainText('simulated')
  const rows = await page.locator('.notification-history tbody tr').count()
  await page.getByRole('button', { name: /^Simulate fee reminders/ }).click()
  await expect(page.getByRole('status')).toContainText('Duplicate')
  await expect(page.locator('.notification-history tbody tr')).toHaveCount(rows)
  await page
    .getByLabel('Announcement message')
    .fill('New evening study slots are available from Monday.')
  await page
    .locator('section')
    .filter({ has: page.getByRole('heading', { name: 'Announcement to All Students' }) })
    .getByRole('button', { name: 'Save draft' })
    .click()
  await expect(page.getByRole('status')).toContainText('Draft saved')
  await page.reload()
  await expect(page.getByLabel('Announcement message')).toHaveValue(
    'New evening study slots are available from Monday.',
  )
  await page.getByRole('button', { name: 'Simulate announcement to all', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('simulated')
  await page.getByLabel('Alert message').fill('Library closes at 6 PM today for maintenance.')
  await page.getByRole('button', { name: 'Simulate alert to all', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('simulated')
  await page.getByLabel('Filter notification history').selectOption('alert')
  await expect(page.locator('.notification-history tbody tr').first()).toContainText('alert')
  await page.screenshot({ path: 'artifacts/notifications-updated-desktop.png', fullPage: true })

  await go('Timings & Plans')
  await page.getByRole('button', { name: 'Edit opening hours' }).click()
  await page.getByLabel('Closed on Sunday', { exact: true }).check()
  await page.getByRole('button', { name: 'Save opening hours' }).click()
  await expect(page.getByRole('status')).toContainText('opening hours saved')
  await page.getByLabel('Availability date').fill('2026-09-20')
  await expect(page.getByText('Closed for this day', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Edit study hours for Priya Sharma', exact: true }).click()
  await page.getByLabel('Daily start time').fill('09:00')
  await page.getByLabel('Daily study hours').fill('4.5')
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.reload()
  const row = page.locator('.study-hours-table tbody tr').filter({ hasText: 'Priya Sharma' })
  await expect(row).toContainText('4.5')
  await expect(row).toContainText(/01:30|1:30/)
  await page.screenshot({ path: 'artifacts/availability-desktop.png', fullPage: true })
  await page.getByRole('button', { name: 'Edit study hours for Priya Sharma', exact: true }).click()
  await expect(page.getByLabel('Daily study hours')).toHaveValue('4.5')
  await page.getByLabel('Daily study hours').fill('')
  await page.getByLabel('Daily start time').fill('08:00')
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByRole('button', { name: 'Edit opening hours' }).click()
  await page.getByLabel('Closed on Sunday', { exact: true }).uncheck()
  await page.getByRole('button', { name: 'Save opening hours' }).click()
  await expect(page.getByRole('status')).toContainText('opening hours saved')
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.locator('body')).toHaveJSProperty('scrollWidth', 390)
  await page.getByRole('button', { name: 'Open navigation' }).click()
  await go('Notifications')
  await expect(page.locator('body')).toHaveJSProperty('scrollWidth', 390)
  await page.screenshot({ path: 'artifacts/notifications-updated-mobile.png', fullPage: true })
})
